### PR TITLE
Added Convolutor Class

### PR DESCRIPTION
**Pull request by genious97**
I wrote up a class that accepts a kernel as a 2d array of doubles. If you feel anything needs to be changed or think any part is incorrect, please feel free to message me or comment on here.

### CODE REVIEW

**Review by andrewyancey — COMMENTED** [review]
I'm having an issue where after pulling this PR to my local repo the class is not added to the project, and it seems to have trouble with your lambdas inside the ByteArrayPoint. Maybe this is an issue with the C# version?

**Comment by genious97** [comment]
Okay would you like me to convert them to fully expanded getters/setters rather than my shorthand. As well to access them you can only use the Capital ones and I will change the lower cased ones to underscore private variables

**Comment by genious97** [comment]
The ByteArrayPoints were only a way to create a connection between the pixels and their distance from the relative pixel.

**Comment by andrewyancey** [comment]
No it's fine. I realized that I was just working with an older version of C# than you were. I think I got it fixed now.

**Comment by genious97** [comment]
I'll look into the class project issue on my machine tomorrow

**Comment by andrewyancey** [comment]
Okay, I just double checked by deleting the local branch and then starting over by pulling your PR, and the convolution class does not seem to be added to the solution for some reason. You might try making a local branch from your PR and see if the issue persists on your end. That's weird.

**Comment by andrewyancey** [comment]
So I tried to fix this for you and co-author you into the merge, but for some stupid reason github won't let me do that and still tag you as a contributor. To make things worse it closed your PR, and even though I reverted the merge, it still won't let me reopen your PR. Sorry.

**Comment by genious97** [comment]
No that's fine, Ill still look into it in the morning

**Comment by andrewyancey** [comment]
Yeah just make a new PR and I'll merge it.

**Pull request merged**
